Axxes.Haxx/Axxes.Haxx/Models/SessionViewModel.cs
using Axxes.Haxx.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace Axxes.Haxx.Models
{
    public class SessionViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime Date { get; set; }
        public string Category { get; set; }
        public ApplicationUser Speaker { get; set; }
        public ICollection<Comment> Comments { get; set; }
        public bool IsPublic { get; set; }

        public static Expression<Func<Session, SessionViewModel>> ViewModel
        {
            get
            {
                return session => new SessionViewModel
                {
                    Id = session.Id,
                    Title = session.Title,
                    Date = session.Date,
                    Speaker = session.Speaker,
                    Category = session.Category,
                    IsPublic = session.IsPublic
                };
            }
        }
    }
}

Axxes.Haxx/Axxes.Haxx/Controllers/SessionController.cs
using Axxes.Haxx.EntityFramework;
using Axxes.Haxx.EntityFramework.Data;
using Axxes.Haxx.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Security.Claims;

namespace Axxes.Haxx.Controllers
{
    [Authorize]
    public class SessionController : BaseController
    {
        public SessionController(ApplicationDbContext db, UserManager<ApplicationUser> userManager) : base(db, userManager)
        {
        }

        public IActionResult Create()
        {
            return View("CreateSessionViewModel");
        }

        [HttpPost]
        public IActionResult Create(SessionInputViewModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                var currentUser = this.User.FindFirst(ClaimTypes.NameIdentifier);
                var currentUserId = currentUser?.Value;

                var newSession = new Session
                {
                    Title = model.Title,
                    Date = model.Date,
                    Description = model.Description,
                    SpeakerId = currentUserId,
                    Category = model.Category,
                    IsPublic = model.IsPublic
                };

                Db.Add(newSession);
                Db.SaveChanges();

                return RedirectToAction("MySessions");
            }

            return View("CreateSessionViewModel");
        }

        public IActionResult MySessions()
        {
            var currentUser = this.User.FindFirst(ClaimTypes.NameIdentifier);
            var currentUserId = currentUser?.Value;

            var sessions = this.Db.Sessions
                .Where(session => session.SpeakerId == currentUserId)
                .OrderBy(session => session.Date)
                .Select(SessionViewModel.ViewModel);

            var upcomingPersonalSessions = sessions.Where(session => session.Date >= DateTime.UtcNow);
            var passedPersonalSessions = sessions.Where(session => session.Date < DateTime.UtcNow);

            return View("MySessionsViewModel", new UpcomingPassedSessionsViewModel
            {
                UpcomingSessions = upcomingPersonalSessions,
                PassedSessions = passedPersonalSessions
            });
        }

        public IActionResult Edit(int id)
        {
            var session = this.Db.Sessions
            .Where(session => session.Id == id)
            .Select(SessionViewModel.ViewModel)
            .FirstOrDefault();

            var sessionDetail = this.Db.Sessions
                .Where(session => session.Id == id)
                .Select(SessionDetailsViewModel.ViewModel)
                .FirstOrDefault();

            return View("EditSessionViewModel", new SessionInputViewModel
            {
                Title = session.Title,
                Category = session.Category,
                Date = session.Date,
                IsPublic = session.IsPublic,
                Description = sessionDetail.Description
            });
        }

        [HttpPost]
        public IActionResult Edit(SessionInputViewModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                var currentUser = this.User.FindFirst(ClaimTypes.NameIdentifier);
                var currentUserId = currentUser?.Value;

                var editSession = new Session
                {
                    Title = model.Title,
                    Date = model.Date,
                    Description = model.Description,
                    SpeakerId = currentUserId,
                    Category = model.Category,
                    IsPublic = model.IsPublic
                };

                Db.Add(editSession);
                Db.SaveChanges();

                return RedirectToAction("MySessions");
            }

            return View("EditSessionViewModel", model);
        }

        public IActionResult Delete(int id)
        {
            var session = this.Db.Sessions
                .Where(session => session.Id == id)
                .Select(SessionViewModel.ViewModel)
                .FirstOrDefault();

            var sessionDetail = this.Db.Sessions
                .Where(session => session.Id == id)
                .Select(SessionDetailsViewModel.ViewModel)
                .FirstOrDefault();

            return View("DeleteSessionViewModel", new SessionInputViewModel
            {
                Title = session.Title,
                Category = session.Category,
                Date = session.Date,
                IsPublic = session.IsPublic,
                Description = sessionDetail.Description
            });
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteSession(int id)
        {
            var session = this.Db.Sessions
                .Where(session => session.Id == id)
                .FirstOrDefault();
            if (session != null)
            {
                Db.Sessions.Remove(session);
                Db.SaveChanges();
            }
            return RedirectToAction("MySessions");
        }
    }
}

Axxes.Haxx/Axxes.Haxx/Views/Session/CreateSessionViewModel.cshtml
@model Axxes.Haxx.Models.SessionInputViewModel

@{
    ViewData["Title"] = "Create Session";
}

<h1>Create Session</h1>

<h4>Input</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPublic" checked="checked"/> @Html.DisplayNameFor(model => model.IsPublic)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create session" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "MySessions", "Session", null, new { @class = "btn" })
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Axxes.Haxx/Axxes.Haxx/Views/Session/DeleteSessionViewModel.cshtml
@model Axxes.Haxx.Models.SessionInputViewModel

<h3>Are you sure you want to delete this?</h3>
<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPublic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPublic)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Axxes.Haxx/Axxes.Haxx/Views/Session/EditSessionViewModel.cshtml
@model Axxes.Haxx.Models.SessionInputViewModel

<h4>SessionInputViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPublic" /> @Html.DisplayNameFor(model => model.IsPublic)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Axxes.Haxx/Axxes.Haxx/Views/Session/MySessionsViewModel.cshtml
@model UpcomingPassedSessionsViewModel

<partial name="_Sessions" />

@section scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js" integrity="sha512-DedNBWPF0hLGUPNbCYfj8qjlEnNE92Fqn7xd3Sscfu7ipy7Zu33unHdugqRD3c4Vj7/yLv+slqZhMls/4Oc7Zg==" crossorigin="anonymous"></script>
}